using Unity.Entities;
using Unity.Mathematics;

/// <summary>
/// Projects requested enemy target positions back onto reachable navigation cells.
/// </summary>
internal static class EnemyNavigationTargetProjectionUtility
{
    #region Constants
    private const int MaximumCellSearchRadius = 16;
    #endregion

    #region Methods

    #region Projection
    /// <summary>
    /// Projects a desired world position to the nearest reachable navigation cell.
    /// </summary>
    /// <param name="desiredPosition">Desired world position before map correction.</param>
    /// <param name="searchDistance">World-space distance used to scale the local recovery search.</param>
    /// <param name="navigationGridState">Shared navigation grid state.</param>
    /// <param name="navigationCells">Shared navigation cells generated by the flow-field system.</param>
    /// <param name="projectedPosition">Output desired position or nearest reachable cell center.</param>
    /// <returns>True when a reachable position was found.</returns>
    public static bool TryProjectToReachablePosition(float3 desiredPosition,
                                                     float searchDistance,
                                                     in EnemyNavigationGridState navigationGridState,
                                                     DynamicBuffer<EnemyNavigationCellElement> navigationCells,
                                                     out float3 projectedPosition)
    {
        projectedPosition = desiredPosition;

        if (!TryResolveClampedCellCoordinates(desiredPosition, in navigationGridState, out int cellX, out int cellY))
            return false;

        int cellIndex = ResolveCellIndex(cellX, cellY, navigationGridState.Width);

        if (IsReachableCell(cellIndex, navigationCells))
        {
            projectedPosition = ResolveCellWorldPosition(desiredPosition.y, in navigationGridState, cellX, cellY);
            return true;
        }

        int searchRadius = ResolveCellSearchRadius(searchDistance, navigationGridState.CellSize);
        float2 desiredPlanar = new float2(desiredPosition.x, desiredPosition.z);
        float bestDistanceSquared = float.MaxValue;
        bool foundReachableCell = false;

        for (int offsetY = -searchRadius; offsetY <= searchRadius; offsetY++)
        {
            for (int offsetX = -searchRadius; offsetX <= searchRadius; offsetX++)
            {
                int candidateX = cellX + offsetX;
                int candidateY = cellY + offsetY;

                if (!IsInsideGrid(candidateX, candidateY, navigationGridState.Width, navigationGridState.Height))
                    continue;

                int candidateIndex = ResolveCellIndex(candidateX, candidateY, navigationGridState.Width);

                if (!IsReachableCell(candidateIndex, navigationCells))
                    continue;

                float2 candidateCenter = ResolveCellCenter(navigationGridState.Origin,
                                                           navigationGridState.CellSize,
                                                           candidateX,
                                                           candidateY);
                float distanceSquared = math.lengthsq(candidateCenter - desiredPlanar);

                if (distanceSquared >= bestDistanceSquared)
                    continue;

                bestDistanceSquared = distanceSquared;
                projectedPosition = new float3(candidateCenter.x, desiredPosition.y, candidateCenter.y);
                foundReachableCell = true;
            }
        }

        return foundReachableCell;
    }
    #endregion

    #region Coordinates
    /// <summary>
    /// Resolves grid coordinates and clamps out-of-grid positions to the nearest border cell.
    /// </summary>
    /// <param name="worldPosition">World position to map.</param>
    /// <param name="navigationGridState">Shared navigation grid state.</param>
    /// <param name="cellX">Output cell X coordinate.</param>
    /// <param name="cellY">Output cell Y coordinate.</param>
    /// <returns>True when the grid has valid dimensions and cell size.</returns>
    private static bool TryResolveClampedCellCoordinates(float3 worldPosition,
                                                         in EnemyNavigationGridState navigationGridState,
                                                         out int cellX,
                                                         out int cellY)
    {
        cellX = 0;
        cellY = 0;

        if (navigationGridState.Width <= 0 || navigationGridState.Height <= 0 || navigationGridState.InverseCellSize <= 0f)
            return false;

        float rawCellX = math.floor((worldPosition.x - navigationGridState.Origin.x) * navigationGridState.InverseCellSize);
        float rawCellY = math.floor((worldPosition.z - navigationGridState.Origin.y) * navigationGridState.InverseCellSize);
        cellX = math.clamp((int)rawCellX, 0, navigationGridState.Width - 1);
        cellY = math.clamp((int)rawCellY, 0, navigationGridState.Height - 1);
        return true;
    }

    /// <summary>
    /// Resolves whether one candidate coordinate is inside the navigation grid.
    /// </summary>
    /// <param name="cellX">Cell X coordinate.</param>
    /// <param name="cellY">Cell Y coordinate.</param>
    /// <param name="width">Grid width.</param>
    /// <param name="height">Grid height.</param>
    /// <returns>True when the coordinate is inside the grid.</returns>
    private static bool IsInsideGrid(int cellX, int cellY, int width, int height)
    {
        return cellX >= 0 && cellY >= 0 && cellX < width && cellY < height;
    }

    /// <summary>
    /// Converts grid coordinates to a linear cell index.
    /// </summary>
    /// <param name="cellX">Cell X coordinate.</param>
    /// <param name="cellY">Cell Y coordinate.</param>
    /// <param name="width">Grid width.</param>
    /// <returns>Linear cell index.</returns>
    private static int ResolveCellIndex(int cellX, int cellY, int width)
    {
        return cellY * width + cellX;
    }
    #endregion

    #region Cells
    /// <summary>
    /// Resolves whether one navigation cell is walkable and connected to the active flow field.
    /// </summary>
    /// <param name="cellIndex">Navigation cell index.</param>
    /// <param name="navigationCells">Shared navigation cells generated by the flow-field system.</param>
    /// <returns>True when the cell is reachable by enemies.</returns>
    private static bool IsReachableCell(int cellIndex, DynamicBuffer<EnemyNavigationCellElement> navigationCells)
    {
        if (cellIndex < 0 || cellIndex >= navigationCells.Length)
            return false;

        EnemyNavigationCellElement cell = navigationCells[cellIndex];
        return cell.Walkable != 0 && cell.Cost != EnemyNavigationFlowFieldUtility.UnreachableCellCost;
    }

    /// <summary>
    /// Resolves the world-space center of a navigation cell while preserving the requested height.
    /// </summary>
    /// <param name="height">World-space height to preserve.</param>
    /// <param name="navigationGridState">Shared navigation grid state.</param>
    /// <param name="cellX">Cell X coordinate.</param>
    /// <param name="cellY">Cell Y coordinate.</param>
    /// <returns>World-space cell center.</returns>
    private static float3 ResolveCellWorldPosition(float height,
                                                   in EnemyNavigationGridState navigationGridState,
                                                   int cellX,
                                                   int cellY)
    {
        float2 center = ResolveCellCenter(navigationGridState.Origin,
                                          navigationGridState.CellSize,
                                          cellX,
                                          cellY);
        return new float3(center.x, height, center.y);
    }

    /// <summary>
    /// Resolves the planar center of a navigation cell.
    /// </summary>
    /// <param name="origin">Navigation grid origin.</param>
    /// <param name="cellSize">Navigation cell size.</param>
    /// <param name="cellX">Cell X coordinate.</param>
    /// <param name="cellY">Cell Y coordinate.</param>
    /// <returns>Planar cell center.</returns>
    private static float2 ResolveCellCenter(float2 origin, float cellSize, int cellX, int cellY)
    {
        float safeCellSize = math.max(0.01f, cellSize);
        return origin + new float2((cellX + 0.5f) * safeCellSize,
                                   (cellY + 0.5f) * safeCellSize);
    }

    /// <summary>
    /// Resolves a bounded search radius in navigation cells from a world-space correction distance.
    /// </summary>
    /// <param name="searchDistance">World-space correction distance.</param>
    /// <param name="cellSize">Navigation cell size.</param>
    /// <returns>Search radius in cells.</returns>
    private static int ResolveCellSearchRadius(float searchDistance, float cellSize)
    {
        float safeCellSize = math.max(0.01f, cellSize);
        int radius = (int)math.ceil(math.max(0f, searchDistance) / safeCellSize) + 2;
        return math.clamp(radius, 1, MaximumCellSearchRadius);
    }
    #endregion

    #endregion
}
