#if UNITY_EDITOR || NASHCORE_RUNTIME_SPAWNER_TOOL
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Runtime catalog used by the main-menu enemy spawner tool to expose editable scenes, spawners and wave presets.
/// </summary>
[CreateAssetMenu(fileName = "EnemySpawnerRuntimeCatalog", menuName = "Enemy/Spawner Runtime Catalog", order = 31)]
public sealed class EnemySpawnerRuntimeCatalog : ScriptableObject
{
    #region Constants
    public const string DefaultAssetPath = "Assets/Scriptable Objects/Enemy/Runtime Tool/EnemySpawnerRuntimeCatalog.asset";
    #endregion

    #region Fields

    #region Serialized Fields
    [Header("Scenes")]
    [Tooltip("Scene and subscene entries that contain enemy spawners editable from the runtime main-menu tool.")]
    [SerializeField] private List<EnemySpawnerRuntimeSceneEntry> scenes = new List<EnemySpawnerRuntimeSceneEntry>();

    [Header("Wave Presets")]
    [Tooltip("Wave preset folders that contain EnemyWavePreset assets selectable from the runtime main-menu tool.")]
    [SerializeField] private List<EnemySpawnerRuntimeWavePresetFolderEntry> wavePresetFolders = new List<EnemySpawnerRuntimeWavePresetFolderEntry>();
    #endregion

    #endregion

    #region Properties
    public IReadOnlyList<EnemySpawnerRuntimeSceneEntry> Scenes
    {
        get
        {
            EnsureCollections();
            return scenes;
        }
    }

    public IReadOnlyList<EnemySpawnerRuntimeWavePresetFolderEntry> WavePresetFolders
    {
        get
        {
            EnsureCollections();
            return wavePresetFolders;
        }
    }
    #endregion

    #region Methods

    #region Unity Methods
    /// <summary>
    /// Restores serialized collections when Unity reloads an incomplete asset.
    /// </summary>
    private void OnValidate()
    {
        EnsureCollections();
    }
    #endregion

    #region Public Methods
    /// <summary>
    /// Replaces catalog contents with freshly generated scene and preset data.
    /// </summary>
    /// <param name="sceneEntries">Scene entries generated by the editor setup utility.</param>
    /// <param name="wavePresetFolderEntries">Wave preset folder entries generated by the editor setup utility.</param>
    public void Assign(IReadOnlyList<EnemySpawnerRuntimeSceneEntry> sceneEntries,
                       IReadOnlyList<EnemySpawnerRuntimeWavePresetFolderEntry> wavePresetFolderEntries)
    {
        EnsureCollections();
        scenes.Clear();
        wavePresetFolders.Clear();

        // Copy generated entries so the catalog owns its serialized data.
        if (sceneEntries != null)
        {
            for (int sceneIndex = 0; sceneIndex < sceneEntries.Count; sceneIndex++)
                scenes.Add(sceneEntries[sceneIndex]);
        }

        if (wavePresetFolderEntries != null)
        {
            for (int folderIndex = 0; folderIndex < wavePresetFolderEntries.Count; folderIndex++)
                wavePresetFolders.Add(wavePresetFolderEntries[folderIndex]);
        }
    }

    /// <summary>
    /// Tries to resolve one scene entry by Unity asset GUID.
    /// </summary>
    /// <param name="sceneGuid">Scene asset GUID to find.</param>
    /// <param name="sceneEntry">Resolved scene entry when found.</param>
    /// <returns>True when a matching scene entry exists, otherwise false.</returns>
    public bool TryGetScene(string sceneGuid, out EnemySpawnerRuntimeSceneEntry sceneEntry)
    {
        EnsureCollections();

        for (int sceneIndex = 0; sceneIndex < scenes.Count; sceneIndex++)
        {
            EnemySpawnerRuntimeSceneEntry candidate = scenes[sceneIndex];

            if (!string.Equals(candidate.SceneGuid, sceneGuid, StringComparison.Ordinal))
                continue;

            sceneEntry = candidate;
            return true;
        }

        sceneEntry = null;
        return false;
    }
    #endregion

    #region Helpers
    /// <summary>
    /// Ensures serialized lists are always safe for runtime iteration.
    /// </summary>
    private void EnsureCollections()
    {
        if (scenes == null)
            scenes = new List<EnemySpawnerRuntimeSceneEntry>();

        if (wavePresetFolders == null)
            wavePresetFolders = new List<EnemySpawnerRuntimeWavePresetFolderEntry>();
    }
    #endregion

    #endregion
}

/// <summary>
/// Describes one scene or subscene that owns runtime-editable enemy spawners.
/// </summary>
[Serializable]
public sealed class EnemySpawnerRuntimeSceneEntry
{
    #region Fields

    #region Serialized Fields
    [Tooltip(" scene name shown by the runtime spawner tool.")]
    [SerializeField] private string sceneName;

    [Tooltip("Project-relative Unity scene path used only for diagnostics and editor regeneration.")]
    [SerializeField] private string scenePath;

    [Tooltip("Unity asset GUID of the scene or subscene.")]
    [SerializeField] private string sceneGuid;

    [Tooltip("Enemy spawners found inside this scene or subscene.")]
    [SerializeField] private List<EnemySpawnerRuntimeSpawnerEntry> spawners = new List<EnemySpawnerRuntimeSpawnerEntry>();
    #endregion

    #endregion

    #region Properties
    public string SceneName
    {
        get
        {
            return sceneName;
        }
    }

    public string ScenePath
    {
        get
        {
            return scenePath;
        }
    }

    public string SceneGuid
    {
        get
        {
            return sceneGuid;
        }
    }

    public IReadOnlyList<EnemySpawnerRuntimeSpawnerEntry> Spawners
    {
        get
        {
            EnsureCollections();
            return spawners;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Assigns generated scene metadata and spawner entries.
    /// </summary>
    /// <param name="newSceneName">Display name shown in the runtime tool.</param>
    /// <param name="newScenePath">Project-relative scene path.</param>
    /// <param name="newSceneGuid">Unity scene asset GUID.</param>
    /// <param name="newSpawners">Generated spawner entries contained by the scene.</param>
    public void Assign(string newSceneName,
                       string newScenePath,
                       string newSceneGuid,
                       IReadOnlyList<EnemySpawnerRuntimeSpawnerEntry> newSpawners)
    {
        sceneName = newSceneName;
        scenePath = newScenePath;
        sceneGuid = newSceneGuid;
        EnsureCollections();
        spawners.Clear();

        // Copy spawner entries into serialized storage.
        if (newSpawners == null)
            return;

        for (int spawnerIndex = 0; spawnerIndex < newSpawners.Count; spawnerIndex++)
            spawners.Add(newSpawners[spawnerIndex]);
    }
    #endregion

    #region Helpers
    /// <summary>
    /// Restores missing serialized lists after deserialization.
    /// </summary>
    private void EnsureCollections()
    {
        if (spawners == null)
            spawners = new List<EnemySpawnerRuntimeSpawnerEntry>();
    }
    #endregion

    #endregion
}

/// <summary>
/// Describes one runtime-editable enemy spawner found in a cataloged scene.
/// </summary>
[Serializable]
public sealed class EnemySpawnerRuntimeSpawnerEntry
{
    #region Fields

    #region Serialized Fields
    [Tooltip("Unity scene or SubScene asset GUID that owns the spawner authoring object and matches the baked ECS identity.")]
    [SerializeField] private string ownerSceneGuid;

    [Tooltip("Stable global object identifier baked onto the spawner entity and used by runtime overrides.")]
    [SerializeField] private string spawnerGuid;

    [Tooltip("Scene hierarchy name shown in the runtime tool.")]
    [SerializeField] private string spawnerName;

    [Tooltip("Full scene hierarchy path used to disambiguate spawners with the same name.")]
    [SerializeField] private string hierarchyPath;

    [Tooltip("Default runtime-enabled state authored on the spawner.")]
    [SerializeField] private bool defaultEnabled = true;

    [Tooltip("Unity asset GUID of the default EnemyWavePreset assigned to this spawner.")]
    [SerializeField] private string defaultWavePresetGuid;
    #endregion

    #endregion

    #region Properties
    public string OwnerSceneGuid
    {
        get
        {
            return ownerSceneGuid;
        }
    }

    public string SpawnerGuid
    {
        get
        {
            return spawnerGuid;
        }
    }

    public string SpawnerName
    {
        get
        {
            return spawnerName;
        }
    }

    public string HierarchyPath
    {
        get
        {
            return hierarchyPath;
        }
    }

    public bool DefaultEnabled
    {
        get
        {
            return defaultEnabled;
        }
    }

    public string DefaultWavePresetGuid
    {
        get
        {
            return defaultWavePresetGuid;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Assigns generated spawner metadata used by the runtime tool and ECS override system.
    /// </summary>
    /// <param name="newOwnerSceneGuid">Unity scene or SubScene asset GUID that owns the spawner authoring object.</param>
    /// <param name="newSpawnerGuid">Stable global object identifier.</param>
    /// <param name="newSpawnerName">Display name shown in the runtime tool.</param>
    /// <param name="newHierarchyPath">Full scene hierarchy path.</param>
    /// <param name="newDefaultEnabled">Default runtime-enabled state.</param>
    /// <param name="newDefaultWavePresetGuid">Default EnemyWavePreset asset GUID.</param>
    public void Assign(string newOwnerSceneGuid,
                       string newSpawnerGuid,
                       string newSpawnerName,
                       string newHierarchyPath,
                       bool newDefaultEnabled,
                       string newDefaultWavePresetGuid)
    {
        ownerSceneGuid = newOwnerSceneGuid;
        spawnerGuid = newSpawnerGuid;
        spawnerName = newSpawnerName;
        hierarchyPath = newHierarchyPath;
        defaultEnabled = newDefaultEnabled;
        defaultWavePresetGuid = newDefaultWavePresetGuid;
    }
    #endregion

    #endregion
}

/// <summary>
/// Describes one folder that provides selectable EnemyWavePreset assets.
/// </summary>
[Serializable]
public sealed class EnemySpawnerRuntimeWavePresetFolderEntry
{
    #region Fields

    #region Serialized Fields
    [Tooltip("Project-relative folder path containing EnemyWavePreset assets.")]
    [SerializeField] private string folderPath;

    [Tooltip(" folder label shown in the runtime tool.")]
    [SerializeField] private string displayName;

    [Tooltip("Wave presets contained in this folder.")]
    [SerializeField] private List<EnemySpawnerRuntimeWavePresetEntry> wavePresets = new List<EnemySpawnerRuntimeWavePresetEntry>();
    #endregion

    #endregion

    #region Properties
    public string FolderPath
    {
        get
        {
            return folderPath;
        }
    }

    public string DisplayName
    {
        get
        {
            return displayName;
        }
    }

    public IReadOnlyList<EnemySpawnerRuntimeWavePresetEntry> WavePresets
    {
        get
        {
            EnsureCollections();
            return wavePresets;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Assigns generated folder metadata and contained wave presets.
    /// </summary>
    /// <param name="newFolderPath">Project-relative folder path.</param>
    /// <param name="newDisplayName">Display label shown in the runtime tool.</param>
    /// <param name="newWavePresets">Generated preset entries inside the folder.</param>
    public void Assign(string newFolderPath,
                       string newDisplayName,
                       IReadOnlyList<EnemySpawnerRuntimeWavePresetEntry> newWavePresets)
    {
        folderPath = newFolderPath;
        displayName = newDisplayName;
        EnsureCollections();
        wavePresets.Clear();

        // Copy preset entries into serialized storage.
        if (newWavePresets == null)
            return;

        for (int presetIndex = 0; presetIndex < newWavePresets.Count; presetIndex++)
            wavePresets.Add(newWavePresets[presetIndex]);
    }
    #endregion

    #region Helpers
    /// <summary>
    /// Restores missing serialized lists after deserialization.
    /// </summary>
    private void EnsureCollections()
    {
        if (wavePresets == null)
            wavePresets = new List<EnemySpawnerRuntimeWavePresetEntry>();
    }
    #endregion

    #endregion
}

/// <summary>
/// Describes one selectable EnemyWavePreset in the runtime spawner tool.
/// </summary>
[Serializable]
public sealed class EnemySpawnerRuntimeWavePresetEntry
{
    #region Fields

    #region Serialized Fields
    [Tooltip("Preset display name shown in dropdowns.")]
    [SerializeField] private string presetName;

    [Tooltip("Project-relative asset path used for diagnostics and catalog regeneration.")]
    [SerializeField] private string assetPath;

    [Tooltip("Unity asset GUID used to match UI selections to pre-baked ECS variants.")]
    [SerializeField] private string assetGuid;

    [Tooltip("EnemyWavePreset asset represented by this runtime catalog entry.")]
    [SerializeField] private EnemyWavePreset preset;
    #endregion

    #endregion

    #region Properties
    public string PresetName
    {
        get
        {
            return presetName;
        }
    }

    public string AssetPath
    {
        get
        {
            return assetPath;
        }
    }

    public string AssetGuid
    {
        get
        {
            return assetGuid;
        }
    }

    public EnemyWavePreset Preset
    {
        get
        {
            return preset;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Assigns generated wave preset metadata.
    /// </summary>
    /// <param name="newPresetName">Display name shown in dropdowns.</param>
    /// <param name="newAssetPath">Project-relative asset path.</param>
    /// <param name="newAssetGuid">Unity asset GUID.</param>
    /// <param name="newPreset">Referenced EnemyWavePreset asset.</param>
    public void Assign(string newPresetName,
                       string newAssetPath,
                       string newAssetGuid,
                       EnemyWavePreset newPreset)
    {
        presetName = newPresetName;
        assetPath = newAssetPath;
        assetGuid = newAssetGuid;
        preset = newPreset;
    }
    #endregion

    #endregion
}
#endif
