using Unity.Entities;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

[assembly: RegisterUnityEngineComponentType(typeof(TrailRenderer))]
[assembly: RegisterUnityEngineComponentType(typeof(ParticleSystem))]
[assembly: RegisterUnityEngineComponentType(typeof(ParticleSystemRenderer))]
[assembly: RegisterUnityEngineComponentType(typeof(Animator))]
[assembly: RegisterUnityEngineComponentType(typeof(SkinnedMeshRenderer))]
[assembly: RegisterUnityEngineComponentType(typeof(EnemyGroundIndicatorView))]
[assembly: RegisterUnityEngineComponentType(typeof(MeshRenderer))]
[assembly: RegisterUnityEngineComponentType(typeof(MeshFilter))]
[assembly: RegisterUnityEngineComponentType(typeof(Canvas))]
[assembly: RegisterUnityEngineComponentType(typeof(CanvasScaler))]
[assembly: RegisterUnityEngineComponentType(typeof(Image))]
[assembly: RegisterUnityEngineComponentType(typeof(CanvasRenderer))]
[assembly: RegisterUnityEngineComponentType(typeof(CanvasGroup))]
[assembly: RegisterUnityEngineComponentType(typeof(TextMeshProUGUI))]
[assembly: RegisterUnityEngineComponentType(typeof(PlayerDroppedPowerUpContainerView))]
