using System.Collections.Generic;
using Unity.Entities;
using Unity.Mathematics;
using Unity.Transforms;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Presents spawn-warning rings from the live per-enemy warning state generated by spawn reservations.
/// </summary>
[UpdateInGroup(typeof(PresentationSystemGroup))]
public partial struct EnemySpawnWarningPresentationSystem : ISystem
{
    #region Constants
    private const float MinimumFadeDurationSeconds = 0.0001f;
    private const float MinimumLeadDurationSeconds = 0.0001f;
    private const float MinimumRingWidth = 0.01f;
    private const string UrpParticlesUnlitShaderName = "Universal Render Pipeline/Particles/Unlit";
    private const string UrpUnlitShaderName = "Universal Render Pipeline/Unlit";
    private const string LegacySpritesDefaultShaderName = "Sprites/Default";
    private const string InternalColoredShaderName = "Hidden/Internal-Colored";
    private static readonly int SurfacePropertyId = Shader.PropertyToID("_Surface");
    private static readonly int BlendPropertyId = Shader.PropertyToID("_Blend");
    private static readonly int AlphaClipPropertyId = Shader.PropertyToID("_AlphaClip");
    private static readonly int SrcBlendPropertyId = Shader.PropertyToID("_SrcBlend");
    private static readonly int DstBlendPropertyId = Shader.PropertyToID("_DstBlend");
    private static readonly int CullPropertyId = Shader.PropertyToID("_Cull");
    private static readonly int ZWritePropertyId = Shader.PropertyToID("_ZWrite");
    private static readonly int ZTestPropertyId = Shader.PropertyToID("_ZTest");
    private static readonly int BaseColorPropertyId = Shader.PropertyToID("_BaseColor");
    private static readonly int ColorPropertyId = Shader.PropertyToID("_Color");
    #endregion

    #region Fields
    private static readonly Dictionary<Entity, EnemySpawnWarningRingView> activeViewByEnemy = new Dictionary<Entity, EnemySpawnWarningRingView>(256);
    private static readonly HashSet<Entity> visibleEnemyEntities = new HashSet<Entity>();
    private static readonly List<Entity> enemyEntitiesPendingRecycle = new List<Entity>(256);
    private static readonly Stack<EnemySpawnWarningRingView> pooledViews = new Stack<EnemySpawnWarningRingView>(128);

    private static GameObject runtimeRootObject;
    private static Material sharedWarningMaterial;
    private static bool missingMaterialWarningIssued;
    #endregion

    #region Methods

    #region Lifecycle
    /// <summary>
    /// Requires at least one active warning state before the presentation system starts ticking.
    /// </summary>
    /// <param name="state">Current ECS system state.</param>
    public void OnCreate(ref SystemState state)
    {
        state.RequireForUpdate<EnemySpawnWarningState>();
    }

    /// <summary>
    /// Renders each currently active spawn-warning ring and recycles views once their warning state expires.
    /// </summary>
    /// <param name="state">Current ECS system state.</param>
    public void OnUpdate(ref SystemState state)
    {
        EntityManager entityManager = state.EntityManager;
        float elapsedTime = (float)SystemAPI.Time.ElapsedTime;
        visibleEnemyEntities.Clear();

        foreach ((RefRO<EnemySpawnWarningState> warningState,
                  Entity enemyEntity) in SystemAPI.Query<RefRO<EnemySpawnWarningState>>()
                                                 .WithEntityAccess())
        {
            EnemySpawnWarningState currentWarningState = warningState.ValueRO;

            if (ShouldDisableWarningState(in currentWarningState, elapsedTime))
            {
                entityManager.SetComponentEnabled<EnemySpawnWarningState>(enemyEntity, false);
                continue;
            }

            if (!TryResolveWarningVisualState(in currentWarningState,
                                              elapsedTime,
                                              out float opacity,
                                              out float widthScale))
            {
                continue;
            }

            EnemySpawnWarningRingView view = GetOrCreateView(enemyEntity);

            if (view == null)
                continue;

            float3 warningPosition = currentWarningState.WorldPosition;
            Vector3 worldPosition = new Vector3(warningPosition.x,
                                                warningPosition.y + math.max(0f, currentWarningState.HeightOffset),
                                                warningPosition.z);
            Color ringColor = new Color(currentWarningState.Color.x,
                                        currentWarningState.Color.y,
                                        currentWarningState.Color.z,
                                        currentWarningState.Color.w);

            view.Render(worldPosition,
                        currentWarningState.Radius,
                        math.max(MinimumRingWidth, currentWarningState.RingWidth),
                        ringColor,
                        opacity,
                        widthScale);
            visibleEnemyEntities.Add(enemyEntity);
        }

        RecycleHiddenViews();
    }

    /// <summary>
    /// Releases all pooled runtime objects allocated by the warning presentation system.
    /// </summary>
    /// <param name="state">Current ECS system state.</param>
    public void OnDestroy(ref SystemState state)
    {
        DestroyRuntimeState();
    }

    /// <summary>
    /// Destroys every runtime warning-ring object and material owned by the static presentation pool.
    /// </summary>
    public static void DestroyRuntimeState()
    {
        DestroyAllViews();
        DestroySharedMaterial();
        DestroyRuntimeRoot();
    }
    #endregion

    #region Rendering
    /// <summary>
    /// Resolves whether one warning state should be disabled because it can no longer produce visible output.
    /// </summary>
    /// <param name="warningState">Current warning payload stored on the enemy.</param>
    /// <param name="elapsedTime">Current elapsed world time.</param>
    /// <returns>True when the warning state should be disabled immediately, otherwise false.</returns>
    private static bool ShouldDisableWarningState(in EnemySpawnWarningState warningState, float elapsedTime)
    {
        if (warningState.MaximumAlpha <= 0f)
            return true;

        if (warningState.Radius <= 0f)
            return true;

        if (warningState.RingWidth <= 0f)
            return true;

        return elapsedTime > warningState.FadeOutEndTime;
    }

    /// <summary>
    /// Resolves the live opacity and width scale of one warning at the current frame.
    /// </summary>
    /// <param name="warningState">Current warning payload stored on the enemy.</param>
    /// <param name="elapsedTime">Current elapsed world time.</param>
    /// <param name="opacity">Resolved output opacity for the current frame.</param>
    /// <param name="widthScale">Resolved output width multiplier for the current frame.</param>
    /// <returns>True when the warning should be visible during this frame, otherwise false.</returns>
    private static bool TryResolveWarningVisualState(in EnemySpawnWarningState warningState,
                                                     float elapsedTime,
                                                     out float opacity,
                                                     out float widthScale)
    {
        if (elapsedTime < warningState.WarningStartTime || elapsedTime > warningState.FadeOutEndTime)
        {
            opacity = 0f;
            widthScale = 0f;
            return false;
        }

        if (elapsedTime <= warningState.SpawnTime)
        {
            float normalizedProgress = warningState.LeadTimeSeconds <= 0f
                ? 1f
                : math.saturate((elapsedTime - warningState.WarningStartTime) / math.max(MinimumLeadDurationSeconds, warningState.LeadTimeSeconds));
            float smoothedProgress = normalizedProgress * normalizedProgress * (3f - 2f * normalizedProgress);
            opacity = warningState.MaximumAlpha * math.lerp(0.18f, 1f, smoothedProgress);
            widthScale = math.lerp(0.8f, 1.18f, smoothedProgress);
            return true;
        }

        if (warningState.FadeOutSeconds <= 0f)
        {
            opacity = 0f;
            widthScale = 0f;
            return false;
        }

        float normalizedFade = 1f - math.saturate((elapsedTime - warningState.SpawnTime) / math.max(MinimumFadeDurationSeconds, warningState.FadeOutSeconds));
        opacity = warningState.MaximumAlpha * normalizedFade;
        widthScale = math.lerp(0.82f, 1.18f, normalizedFade);
        return opacity > 0f;
    }
    #endregion

    #region View Pool
    /// <summary>
    /// Resolves an existing warning view for the enemy or creates a new pooled one when needed.
    /// </summary>
    /// <param name="enemyEntity">Enemy that currently owns the warning state.</param>
    /// <returns>Runtime ring view associated with the provided enemy.</returns>
    private static EnemySpawnWarningRingView GetOrCreateView(Entity enemyEntity)
    {
        if (activeViewByEnemy.TryGetValue(enemyEntity, out EnemySpawnWarningRingView activeView))
            return activeView;

        EnemySpawnWarningRingView view = AcquireView();

        if (view == null)
            return null;

        activeViewByEnemy.Add(enemyEntity, view);
        return view;
    }

    /// <summary>
    /// Returns hidden pooled views back to the free stack once they are no longer visible this frame.
    /// </summary>
    private static void RecycleHiddenViews()
    {
        enemyEntitiesPendingRecycle.Clear();

        foreach (KeyValuePair<Entity, EnemySpawnWarningRingView> pair in activeViewByEnemy)
        {
            if (visibleEnemyEntities.Contains(pair.Key) && pair.Value != null)
                continue;

            if (pair.Value != null)
            {
                pair.Value.Deactivate();
                pooledViews.Push(pair.Value);
            }

            enemyEntitiesPendingRecycle.Add(pair.Key);
        }

        for (int entityIndex = 0; entityIndex < enemyEntitiesPendingRecycle.Count; entityIndex++)
            activeViewByEnemy.Remove(enemyEntitiesPendingRecycle[entityIndex]);
    }

    /// <summary>
    /// Acquires one pooled warning ring view or creates a new one when the pool is empty.
    /// </summary>
    /// <returns>Runtime warning ring view ready for rendering, or null when creation failed.</returns>
    private static EnemySpawnWarningRingView AcquireView()
    {
        Material warningMaterial = ResolveSharedWarningMaterial();

        if (warningMaterial == null)
            return null;

        while (pooledViews.Count > 0)
        {
            EnemySpawnWarningRingView pooledView = pooledViews.Pop();

            if (pooledView == null)
                continue;

            Transform runtimeRootTransform = ResolveRuntimeRootTransform();

            if (pooledView.transform.parent != runtimeRootTransform)
                pooledView.transform.SetParent(runtimeRootTransform, false);

            pooledView.Initialize(warningMaterial);
            return pooledView;
        }

        GameObject viewObject = new GameObject("EnemySpawnWarningRingView");
        viewObject.hideFlags = HideFlags.HideAndDontSave;
        Transform createdRootTransform = ResolveRuntimeRootTransform();

        if (createdRootTransform != null)
            viewObject.transform.SetParent(createdRootTransform, false);

        EnemySpawnWarningRingView createdView = viewObject.AddComponent<EnemySpawnWarningRingView>();
        createdView.Initialize(warningMaterial);
        createdView.Deactivate();
        return createdView;
    }

    /// <summary>
    /// Destroys every active or pooled warning view immediately.
    /// </summary>
    private static void DestroyAllViews()
    {
        foreach (KeyValuePair<Entity, EnemySpawnWarningRingView> pair in activeViewByEnemy)
        {
            if (pair.Value != null)
                Object.DestroyImmediate(pair.Value.gameObject);
        }

        activeViewByEnemy.Clear();

        while (pooledViews.Count > 0)
        {
            EnemySpawnWarningRingView pooledView = pooledViews.Pop();

            if (pooledView == null)
                continue;

            Object.DestroyImmediate(pooledView.gameObject);
        }

        visibleEnemyEntities.Clear();
        enemyEntitiesPendingRecycle.Clear();
    }
    #endregion

    #region Runtime Resources
    /// <summary>
    /// Resolves the hidden runtime root used to parent every pooled warning view.
    /// </summary>
    /// <returns>Runtime root transform used by warning views.</returns>
    private static Transform ResolveRuntimeRootTransform()
    {
        if (runtimeRootObject == null)
        {
            runtimeRootObject = new GameObject("EnemySpawnWarningRuntimeRoot");
            runtimeRootObject.hideFlags = HideFlags.HideAndDontSave;
        }

        return runtimeRootObject.transform;
    }

    /// <summary>
    /// Destroys the hidden runtime root when the system shuts down.
    /// </summary>
    private static void DestroyRuntimeRoot()
    {
        if (runtimeRootObject == null)
            return;

        Object.DestroyImmediate(runtimeRootObject);
        runtimeRootObject = null;
    }

    /// <summary>
    /// Resolves the shared material assigned to every pooled LineRenderer.
    /// </summary>
    /// <returns>Shared runtime material used by warning views.</returns>
    private static Material ResolveSharedWarningMaterial()
    {
        if (sharedWarningMaterial != null)
            return sharedWarningMaterial;

        Shader lineShader = ResolveFallbackLineShader();

        if (lineShader == null)
        {
            LogMissingLineShaderWarning();
            return null;
        }

        sharedWarningMaterial = new Material(lineShader);
        ConfigureWarningMaterial(sharedWarningMaterial);
        return sharedWarningMaterial;
    }

    /// <summary>
    /// Resolves a build-safe shader fallback when the built-in sprite material cannot be loaded.
    /// </summary>
    /// <returns>First supported line-renderer shader found in the current project.</returns>
    private static Shader ResolveFallbackLineShader()
    {
        Shader lineShader = Shader.Find(UrpParticlesUnlitShaderName);

        if (lineShader != null)
            return lineShader;

        lineShader = Shader.Find(UrpUnlitShaderName);

        if (lineShader != null)
            return lineShader;

        lineShader = Shader.Find(LegacySpritesDefaultShaderName);

        if (lineShader != null)
            return lineShader;

        return Shader.Find(InternalColoredShaderName);
    }

    /// <summary>
    /// Applies transparent line-renderer settings to the shared warning material.
    /// </summary>
    /// <param name="warningMaterial">Runtime material used by pooled warning rings.</param>
    private static void ConfigureWarningMaterial(Material warningMaterial)
    {
        warningMaterial.hideFlags = HideFlags.HideAndDontSave;
        warningMaterial.name = "EnemySpawnWarningRing_Runtime";
        SetFloatIfPresent(warningMaterial, SurfacePropertyId, 1f);
        SetFloatIfPresent(warningMaterial, BlendPropertyId, 0f);
        SetFloatIfPresent(warningMaterial, AlphaClipPropertyId, 0f);
        SetFloatIfPresent(warningMaterial, SrcBlendPropertyId, (float)BlendMode.SrcAlpha);
        SetFloatIfPresent(warningMaterial, DstBlendPropertyId, (float)BlendMode.OneMinusSrcAlpha);
        SetFloatIfPresent(warningMaterial, CullPropertyId, (float)CullMode.Off);
        SetFloatIfPresent(warningMaterial, ZWritePropertyId, 0f);
        SetFloatIfPresent(warningMaterial, ZTestPropertyId, (float)CompareFunction.Always);
        SetColorIfPresent(warningMaterial, BaseColorPropertyId, Color.white);
        SetColorIfPresent(warningMaterial, ColorPropertyId, Color.white);
        warningMaterial.renderQueue = (int)RenderQueue.Transparent + 120;
    }

    /// <summary>
    /// Sets one material float only when the active shader exposes the requested property.
    /// </summary>
    /// <param name="material">Runtime material being configured.</param>
    /// <param name="propertyId">Shader property id.</param>
    /// <param name="value">Float value to assign.</param>
    private static void SetFloatIfPresent(Material material, int propertyId, float value)
    {
        if (!material.HasProperty(propertyId))
            return;

        material.SetFloat(propertyId, value);
    }

    /// <summary>
    /// Sets one material color only when the active shader exposes the requested property.
    /// </summary>
    /// <param name="material">Runtime material being configured.</param>
    /// <param name="propertyId">Shader property id.</param>
    /// <param name="value">Color value to assign.</param>
    private static void SetColorIfPresent(Material material, int propertyId, Color value)
    {
        if (!material.HasProperty(propertyId))
            return;

        material.SetColor(propertyId, value);
    }

    /// <summary>
    /// Logs one warning when no supported runtime shader can be found for spawn-warning rings.
    /// </summary>
    private static void LogMissingLineShaderWarning()
    {
        if (missingMaterialWarningIssued)
            return;

        missingMaterialWarningIssued = true;
        Debug.LogWarning("[EnemySpawnWarningPresentationSystem] No supported line-renderer shader was found. Spawn warning rings will stay hidden until a URP Unlit, URP Particles Unlit, Sprites/Default, or Hidden/Internal-Colored shader is available.");
    }

    /// <summary>
    /// Destroys the shared runtime material when the system shuts down.
    /// </summary>
    private static void DestroySharedMaterial()
    {
        if (sharedWarningMaterial == null)
            return;

        Object.DestroyImmediate(sharedWarningMaterial);
        sharedWarningMaterial = null;
    }
    #endregion

    #endregion
}
