using Unity.Entities;
using Unity.Mathematics;

/// <summary>
/// Keeps Bombardier landing targets inside reachable map space when navigation data is available.
/// </summary>
internal static class EnemyBombardierMapSafetyUtility
{
    #region Methods

    #region Landing Projection
    /// <summary>
    /// Projects one Bombardier landing point back inside the reachable map when navigation data is available.
    /// </summary>
    /// <param name="landingPosition">Requested landing position.</param>
    /// <param name="fallbackPosition">Fallback position used when the requested point cannot be projected.</param>
    /// <param name="bombardierConfig">Bombardier config used to size the projection search.</param>
    /// <param name="navigationReady">True when map projection can use the shared navigation grid.</param>
    /// <param name="navigationGridState">Shared navigation grid state.</param>
    /// <param name="navigationCells">Shared navigation cells generated by the flow-field system.</param>
    /// <returns>Map-safe landing position when projection succeeds, otherwise the original landing position.</returns>
    public static float3 ResolveMapSafeLandingPosition(float3 landingPosition,
                                                       float3 fallbackPosition,
                                                       in EnemyBombardierConfigElement bombardierConfig,
                                                       bool navigationReady,
                                                       in EnemyNavigationGridState navigationGridState,
                                                       DynamicBuffer<EnemyNavigationCellElement> navigationCells)
    {
        if (!navigationReady)
            return landingPosition;

        float searchDistance = ResolveLandingProjectionSearchDistance(in bombardierConfig);

        if (EnemyNavigationTargetProjectionUtility.TryProjectToReachablePosition(landingPosition,
                                                                                 searchDistance,
                                                                                 in navigationGridState,
                                                                                 navigationCells,
                                                                                 out float3 projectedLandingPosition))
        {
            return projectedLandingPosition;
        }

        if (EnemyNavigationTargetProjectionUtility.TryProjectToReachablePosition(fallbackPosition,
                                                                                 searchDistance,
                                                                                 in navigationGridState,
                                                                                 navigationCells,
                                                                                 out float3 projectedFallbackPosition))
        {
            return projectedFallbackPosition;
        }

        return landingPosition;
    }
    #endregion

    #region Helpers
    /// <summary>
    /// Resolves a projection search radius that covers random target distance and launch-pattern spread.
    /// </summary>
    /// <param name="bombardierConfig">Bombardier config containing random and pattern radii.</param>
    /// <returns>World-space search distance used by navigation projection.</returns>
    private static float ResolveLandingProjectionSearchDistance(in EnemyBombardierConfigElement bombardierConfig)
    {
        float searchDistance = math.max(math.max(0f, bombardierConfig.RandomMaximumDistance),
                                        math.max(0f, bombardierConfig.LandingSpreadRadius));
        searchDistance = math.max(searchDistance, math.max(0f, bombardierConfig.RadialPatternRadius));
        return math.max(searchDistance, math.max(0f, bombardierConfig.DamageRadius));
    }
    #endregion

    #endregion
}
