using System;
using UnityEngine;

/// <summary>
/// Stores one field selected for import or export, including the stable brush path used by workbook mappings.
/// </summary>
[Serializable]
public sealed class ExcelDataFieldSelection
{
    #region Fields

    #region Serialized Fields
    [Tooltip("Stable catalog field identifier generated from domain, asset type and serialized path.")]
    [SerializeField] private string fieldId;

    [Tooltip("Human-readable label shown in filter results and brush dropdowns.")]
    [SerializeField] private string displayName;

    [Tooltip("Unity serialized property path used to read or write this value on the target object.")]
    [SerializeField] private string serializedPath;

    [Tooltip("Template path where concrete list indexes are replaced by list tokens for reusable mappings.")]
    [SerializeField] private string pathTemplate;

    [Tooltip("Management domain that owns this field.")]
    [SerializeField] private ExcelDataTransferDomain domain;

    [Tooltip("Value family used by brush filters and workbook formatting defaults.")]
    [SerializeField] private ExcelDataBrushDataKind dataKind;

    [Tooltip("True when this field can be imported from a workbook into Unity authoring data.")]
    [SerializeField] private bool importEnabled = true;

    [Tooltip("True when this field can be exported from Unity authoring data into a workbook.")]
    [SerializeField] private bool exportEnabled = true;
    #endregion

    #endregion

    #region Properties
    public string FieldId
    {
        get
        {
            return fieldId;
        }
    }

    public string DisplayName
    {
        get
        {
            return displayName;
        }
    }

    public string SerializedPath
    {
        get
        {
            return serializedPath;
        }
    }

    public string PathTemplate
    {
        get
        {
            return pathTemplate;
        }
    }

    public ExcelDataTransferDomain Domain
    {
        get
        {
            return domain;
        }
    }

    public ExcelDataBrushDataKind DataKind
    {
        get
        {
            return dataKind;
        }
    }

    public bool ImportEnabled
    {
        get
        {
            return importEnabled;
        }
    }

    public bool ExportEnabled
    {
        get
        {
            return exportEnabled;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Copies catalog metadata into this serializable field selection.
    /// </summary>
    /// <param name="newFieldId">Stable field id generated by the field catalog.</param>
    /// <param name="newDisplayName">Readable label shown in dropdowns and lists.</param>
    /// <param name="newSerializedPath">Concrete Unity serialized property path.</param>
    /// <param name="newPathTemplate">Reusable path where concrete list indexes are tokenized.</param>
    /// <param name="newDomain">Domain that owns the field.</param>
    /// <param name="newDataKind">Value kind used by filters and formatters.</param>
    public void Configure(string newFieldId,
                          string newDisplayName,
                          string newSerializedPath,
                          string newPathTemplate,
                          ExcelDataTransferDomain newDomain,
                          ExcelDataBrushDataKind newDataKind)
    {
        fieldId = newFieldId;
        displayName = newDisplayName;
        serializedPath = newSerializedPath;
        pathTemplate = newPathTemplate;
        domain = newDomain;
        dataKind = newDataKind;
    }

    /// <summary>
    /// Updates import/export flags for this field selection without changing catalog identity metadata.
    /// </summary>
    /// <param name="newImportEnabled">True when this field can participate in import operations.</param>
    /// <param name="newExportEnabled">True when this field can participate in export operations.</param>
    public void ConfigureDirection(bool newImportEnabled, bool newExportEnabled)
    {
        importEnabled = newImportEnabled;
        exportEnabled = newExportEnabled;
    }
    #endregion

    #endregion
}

/// <summary>
/// Stores one workbook cell mapping painted in the layout designer grid.
/// </summary>
[Serializable]
public sealed class ExcelDataCellBrushMapping
{
    #region Fields

    #region Serialized Fields
    [Tooltip("Worksheet name that owns this painted cell mapping.")]
    [SerializeField] private string sheetName = "Objects";

    [Tooltip("One-based row index matching the corresponding Excel row.")]
    [Min(1)]
    [SerializeField] private int rowIndex = 1;

    [Tooltip("One-based column index matching the corresponding Excel column.")]
    [Min(1)]
    [SerializeField] private int columnIndex = 1;

    [Tooltip("Field catalog identifier painted into this workbook cell.")]
    [SerializeField] private string fieldId;

    [Tooltip("Import/export direction supported by this cell mapping.")]
    [SerializeField] private ExcelDataTransferDirection direction;

    [Tooltip("Optional column or cell header override written during export.")]
    [SerializeField] private string headerOverride;

    [Tooltip("Optional Excel number format applied when this cell is exported.")]
    [SerializeField] private string customNumberFormat;
    #endregion

    #endregion

    #region Properties
    public string SheetName
    {
        get
        {
            return sheetName;
        }
    }

    public int RowIndex
    {
        get
        {
            return rowIndex;
        }
    }

    public int ColumnIndex
    {
        get
        {
            return columnIndex;
        }
    }

    public string FieldId
    {
        get
        {
            return fieldId;
        }
    }

    public ExcelDataTransferDirection Direction
    {
        get
        {
            return direction;
        }
    }

    public string HeaderOverride
    {
        get
        {
            return headerOverride;
        }
    }

    public string CustomNumberFormat
    {
        get
        {
            return customNumberFormat;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Configures this mapping after a field brush is painted into the layout grid.
    /// </summary>
    /// <param name="newSheetName">Worksheet name that owns the painted cell.</param>
    /// <param name="newRowIndex">One-based Excel row index.</param>
    /// <param name="newColumnIndex">One-based Excel column index.</param>
    /// <param name="newFieldId">Field catalog identifier assigned to the cell.</param>
    /// <param name="newDirection">Transfer direction supported by the cell mapping.</param>
    /// <param name="newHeaderOverride">Optional workbook header override.</param>
    /// <param name="newCustomNumberFormat">Optional Excel number format string.</param>
    public void Configure(string newSheetName,
                          int newRowIndex,
                          int newColumnIndex,
                          string newFieldId,
                          ExcelDataTransferDirection newDirection,
                          string newHeaderOverride,
                          string newCustomNumberFormat)
    {
        sheetName = string.IsNullOrWhiteSpace(newSheetName) ? "Objects" : newSheetName;
        rowIndex = newRowIndex;
        columnIndex = newColumnIndex;
        fieldId = newFieldId;
        direction = newDirection;
        headerOverride = newHeaderOverride;
        customNumberFormat = newCustomNumberFormat;
    }

    /// <summary>
    /// Checks whether this mapping targets the provided worksheet cell.
    /// </summary>
    /// <param name="targetSheetName">Worksheet name being searched.</param>
    /// <param name="targetRowIndex">One-based row index being searched.</param>
    /// <param name="targetColumnIndex">One-based column index being searched.</param>
    /// <returns>True when the mapping owns the provided cell coordinate.</returns>
    public bool MatchesCell(string targetSheetName, int targetRowIndex, int targetColumnIndex)
    {
        return string.Equals(sheetName, targetSheetName, StringComparison.Ordinal) &&
               rowIndex == targetRowIndex &&
               columnIndex == targetColumnIndex;
    }

    /// <summary>
    /// Reports whether the mapping has enough data to participate in workbook export.
    /// </summary>
    /// <returns>True when the mapping has a valid cell coordinate and field id.</returns>
    public bool IsUsable()
    {
        if (rowIndex < 1 || columnIndex < 1)
            return false;

        return !string.IsNullOrWhiteSpace(fieldId);
    }
    #endregion

    #endregion
}

/// <summary>
/// Defines one brush shown in the layout designer palette.
/// </summary>
[Serializable]
public sealed class ExcelDataBrushDefinition
{
    #region Fields

    #region Serialized Fields
    [Tooltip("Stable brush identifier used by cell mappings.")]
    [SerializeField] private string brushId;

    [Tooltip("Readable brush name shown in the brush palette.")]
    [SerializeField] private string brushName = "New Brush";

    [Tooltip("Domain filter applied when this brush opens the field picker.")]
    [SerializeField] private ExcelDataTransferDomain domain = ExcelDataTransferDomain.All;

    [Tooltip("Category filter applied when this brush opens the field picker.")]
    [SerializeField] private ExcelDataFieldCategory category = ExcelDataFieldCategory.All;

    [Tooltip("Data kind filter applied when this brush opens the field picker.")]
    [SerializeField] private ExcelDataBrushDataKind dataKind = ExcelDataBrushDataKind.All;

    [Tooltip("List participation filter applied when this brush opens the field picker.")]
    [SerializeField] private ExcelDataListElementFilterMode listFilter = ExcelDataListElementFilterMode.HideConcreteListElements;

    [Tooltip("Source type search text applied when this brush opens the field picker.")]
    [SerializeField] private string sourceFilter;

    [Tooltip("Brush color used by the layout grid cell overlay.")]
    [SerializeField] private Color color = Color.white;

    [Tooltip("Additional search tokens that make this brush easier to find in large palettes.")]
    [SerializeField] private string searchTokens;

    [Tooltip("Short editor-only note describing when this brush should be used.")]
    [SerializeField] private string description;
    #endregion

    #endregion

    #region Properties
    public string BrushId
    {
        get
        {
            return brushId;
        }
    }

    public string BrushName
    {
        get
        {
            return brushName;
        }
    }

    public ExcelDataTransferDomain Domain
    {
        get
        {
            return domain;
        }
    }

    public ExcelDataFieldCategory Category
    {
        get
        {
            return category;
        }
    }

    public ExcelDataBrushDataKind DataKind
    {
        get
        {
            return dataKind;
        }
    }

    public ExcelDataListElementFilterMode ListFilter
    {
        get
        {
            return listFilter;
        }
    }

    public string SourceFilter
    {
        get
        {
            return sourceFilter;
        }
    }

    public Color Color
    {
        get
        {
            return color;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Configures one default brush while preserving the stable identifier if it already exists.
    /// </summary>
    /// <param name="newBrushName">Readable brush name shown in the palette.</param>
    /// <param name="newDomain">Domain filter applied by this brush.</param>
    /// <param name="newCategory">Category filter applied by this brush.</param>
    /// <param name="newDataKind">Data-kind filter applied by this brush.</param>
    /// <param name="newListFilter">List filter applied by this brush.</param>
    /// <param name="newSourceFilter">Source type search applied by this brush.</param>
    /// <param name="newColor">Grid overlay color used by this brush.</param>
    /// <param name="newSearchTokens">Extra text tokens used by smart search.</param>
    /// <param name="newDescription">Short editor note describing this brush.</param>
    public void Configure(string newBrushName,
                          ExcelDataTransferDomain newDomain,
                          ExcelDataFieldCategory newCategory,
                          ExcelDataBrushDataKind newDataKind,
                          ExcelDataListElementFilterMode newListFilter,
                          string newSourceFilter,
                          Color newColor,
                          string newSearchTokens,
                          string newDescription)
    {
        if (string.IsNullOrWhiteSpace(brushId))
            brushId = Guid.NewGuid().ToString("N");

        brushName = newBrushName;
        domain = newDomain;
        category = newCategory;
        dataKind = newDataKind;
        listFilter = newListFilter;
        sourceFilter = newSourceFilter;
        color = newColor;
        searchTokens = newSearchTokens;
        description = newDescription;
    }

    /// <summary>
    /// Ensures the brush has a stable identifier without changing user-authored search or color data.
    /// </summary>
    public void ValidateValues()
    {
        if (string.IsNullOrWhiteSpace(brushId))
            brushId = Guid.NewGuid().ToString("N");

        if (string.IsNullOrWhiteSpace(brushName))
            brushName = "Brush";
    }
    #endregion

    #endregion
}
