using System;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Prevents Move, Rect and Transform tool operations from introducing unintended rotation while Unity grid snapping is enabled.
/// </summary>
[InitializeOnLoad]
internal static class LevelTransformGridGuard
{
    #region Constants

    private const string EnabledPreferenceKey = "NashCore.LevelAuthoring.TransformGridGuard.Enabled";
    private const double NotificationIntervalSeconds = 1d;

    #endregion

    #region Fields

    private static double nextNotificationTime;

    #endregion

    #region Properties

    public static bool Enabled
    {
        get
        {
            return EditorPrefs.GetBool(EnabledPreferenceKey, true);
        }
        set
        {
            EditorPrefs.SetBool(EnabledPreferenceKey, value);
            LevelTransformGridGuardWindow.RepaintOpenWindow();
        }
    }

    public static bool IsProtectionActive
    {
        get
        {
            return Enabled &&
                   !Application.isPlaying &&
                   EditorSnapSettings.gridSnapEnabled &&
                   IsProtectedTool(Tools.current);
        }
    }

    #endregion

    #region Constructors

    /// <summary>
    /// Registers one event-driven Undo modification filter after each editor domain reload.
    /// </summary>
    static LevelTransformGridGuard()
    {
        Undo.postprocessModifications -= RestoreProtectedRotations;
        Undo.postprocessModifications += RestoreProtectedRotations;
    }

    #endregion

    #region Methods

    #region Event Methods

    /// <summary>
    /// Restores rotation property values modified by non-rotation scene tools while grid snapping is active.
    /// </summary>
    /// <param name="modifications">Undo property modifications generated by the current editor operation.</param>
    /// <returns>The same modification array with unintended rotation values restored to their previous state.</returns>
    private static UndoPropertyModification[] RestoreProtectedRotations(UndoPropertyModification[] modifications)
    {
        if (!IsProtectionActive || modifications == null)
            return modifications;

        bool restoredRotation = false;

        // Preserve every non-rotation change while replacing quaternion and Euler-hint mutations in place.
        for (int modificationIndex = 0; modificationIndex < modifications.Length; modificationIndex++)
        {
            UndoPropertyModification modification = modifications[modificationIndex];

            if (!IsProtectedRotationModification(modification))
                continue;

            modification.currentValue.value = modification.previousValue.value;
            modification.currentValue.objectReference = modification.previousValue.objectReference;
            modifications[modificationIndex] = modification;
            restoredRotation = true;
        }

        if (restoredRotation)
            NotifyRotationProtection();

        return modifications;
    }

    #endregion

    #region Detection Methods

    /// <summary>
    /// Determines whether a scene tool should preserve rotation while manipulating another transform channel.
    /// </summary>
    /// <param name="tool">Current Unity editor scene tool.</param>
    /// <returns>True for tools that can move objects and expose accidental rotation changes.</returns>
    private static bool IsProtectedTool(Tool tool)
    {
        switch (tool)
        {
            case Tool.Move:
            case Tool.Rect:
            case Tool.Transform:
                return true;
            default:
                return false;
        }
    }

    /// <summary>
    /// Determines whether one Undo modification targets a Transform rotation serialization path.
    /// </summary>
    /// <param name="modification">Undo modification to inspect.</param>
    /// <returns>True when the current and previous values describe a serialized rotation channel.</returns>
    private static bool IsProtectedRotationModification(UndoPropertyModification modification)
    {
        if (modification.currentValue == null ||
            modification.previousValue == null ||
            !(modification.currentValue.target is Transform))
            return false;

        string propertyPath = modification.currentValue.propertyPath;

        if (string.IsNullOrWhiteSpace(propertyPath))
            return false;

        return propertyPath.StartsWith("m_LocalRotation", StringComparison.Ordinal) ||
               propertyPath.StartsWith("m_LocalEulerAnglesHint", StringComparison.Ordinal) ||
               propertyPath.StartsWith("localEulerAnglesRaw", StringComparison.Ordinal);
    }

    #endregion

    #region Notification Methods

    /// <summary>
    /// Shows one throttled Scene view notification when an unintended rotation is rejected.
    /// </summary>
    private static void NotifyRotationProtection()
    {
        if (EditorApplication.timeSinceStartup < nextNotificationTime)
            return;

        nextNotificationTime = EditorApplication.timeSinceStartup + NotificationIntervalSeconds;
        SceneView sceneView = SceneView.lastActiveSceneView;

        if (sceneView != null)
            sceneView.ShowNotification(new GUIContent("Grid Guard preserved rotation. Use Rotate for intentional changes."));
    }

    #endregion

    #endregion
}
